experiment_name: 22_update_loss_16_24_node_4_6_batch_3_4_batch_size

batch_size: 2
acc_grad: 2
gpus: 2
steps: 1000
num_workers: 8

max_epochs: 10000
max_steps: 200000

val_check_interval: 700
# limit_val_batches: 0.0

include_dense_vis: false
dense_vis_epochs: 0

dataset: oct
oct_root: /data/jeanine/processed_data

train_fraction: 0.7
val_fraction: 0.2
test_fraction: 0.1

# train_num_volumes: 1
val_samples_per_volume: 3
test_samples_per_volume: 1

samples_per_volume: 5
randomize_samples: true

sampling: DDIM
inference_ratio: 20

offline: false
wandb_id: null

backbone_learning_rate: 1e-5
head_learning_rate: 1e-4
backbone_weight_decay: 0.0
head_weight_decay: 1e-4

classifier_free_w: 0.0
classifier_free_prob: 0.0
data_augmentation: none
checkpoint_path: ""
noise_weight: 1.0

predict_xstart: true
rotation: false
only_rotation: false

freeze_backbone: false
visual_pretrained: true
discrete: false
backbone: efficientnet_b0
architecture: transformer
all_equivariant: false

save_eval_images: true

dense_size: 30
crop_l: 180

min_total_nodes: 12
max_total_nodes: 12
min_unique_scans: 8

min_num_batches: 4
max_num_batches: 4
min_batch_size: 3
max_batch_size: 3