experiment_name: oct_360_baseline_frozen

batch_size: 4
gpus: 1
steps: 50
num_workers: 4
max_epochs: 300

learning_rate: 1e-4

include_dense_vis: true
dense_vis_epochs: 2

dataset: oct
oct_root: /data/jeanine/processed_data

sampling: DDIM
inference_ratio: 1

offline: true
wandb_id: null

classifier_free_w: 0.2
classifier_free_prob: 0.0
data_augmentation: none
checkpoint_path: ""
noise_weight: 1.0

predict_xstart: true
rotation: false
only_rotation: false

freeze_backbone: true
visual_pretrained: true
discrete: false
backbone: efficientnet_b0
architecture: transformer
all_equivariant: false

degree: -1
virt_nodes: 4
inf_fully: false
acc_grad: 0
save_eval_images: false

dense_size: 30
crop_l: 120
min_num_batches: 4
max_num_batches: 6
min_batch_size: 3
max_batch_size: 8