experiment_name: 8_test_coord_updates

batch_size: 1
acc_grad: 4
gpus: 2
steps: 1000
num_workers: 8

max_epochs: 10000
max_steps: 200000

val_check_interval: 500

include_dense_vis: true
dense_vis_epochs: 1

dataset: oct
oct_root: /data/jeanine/processed_data

# train_num_volumes: 1
samples_per_volume: 5
randomize_samples: true
rough_condition_dropout: 0.25

sampling: DDIM
inference_ratio: 20

offline: false
wandb_id: null

backbone_learning_rate: 1e-5
head_learning_rate: 1e-4

classifier_free_w: 0.0
classifier_free_prob: 0.0
data_augmentation: none
checkpoint_path: ""
noise_weight: 1.0

predict_xstart: true
rotation: false
only_rotation: false

freeze_backbone: false
visual_pretrained: true
discrete: false
backbone: efficientnet_b0
architecture: transformer
all_equivariant: false

degree: -1
virt_nodes: 4
inf_fully: false
save_eval_images: true

dense_size: 10
crop_l: 200

min_num_batches: 3
max_num_batches: 5
min_batch_size: 3
max_batch_size: 6